### PR TITLE
Updated UserGuide

### PR DESCRIPTION
**Pull request by gx-huang**

### CODE REVIEW

**Review by souwmyaa — COMMENTED** [review]
Looks good!

**Review by wyt-sonia — COMMENTED** [review]
Looks good : )

**Review by wyt-sonia — APPROVED** [review]
Looks good to merge.

**Review by souwmyaa — APPROVED** [review]
Looks good to merge :)

**Comment by teikjun** [comment]
Merged on your behalf so I can work on your version!

**Pull request merged**
